files:
  - source: /source
    translation: /translation/%two_letters_code%/%original_file_name%
    first_line_contains_header: '1'
    scheme: 'none,source_phrase,translation,context'
    labels: ['test', 'test-22', 'test,rr']
