files:
  - source: /source/tr/Ukrainian2.xml
    ignore:
      - /source/test_file.txt
      - /source/coma.csv
    translation: /translation/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        it: Italian
