files:
  - source: source/tr
    ignore:
      - /source/test_file.txt
    translation: /translation/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        it: Italian
  - source: /source
    translation: /translation/%two_letters_code%/%original_file_name%
    first_line_contains_header: '1'
    scheme: 'none,source_phrase,translation,context'
