files:
  - source: /source
    translation: /translation/%two_letters_code%/%original_file_name%
    multilingual_spreadsheet: '1'
    first_line_contains_header: '1'
    scheme: 'identifier,source_phrase,context,max_length,it,uk'
    labels: ['test', 'test-22', 'test,rr']
