files:
  - source: /source
    translation: /translation/%two_letters_code%/%original_file_name%
    multilingual_spreadsheet: '1'
    first_line_contains_header: '1'
    scheme: 'identifier,source_phrase,context,max_length,it,uk'
    translate_content: '0'
    translate_attributes: '0'
    content_segmentation: '0'
    labels: ['test', 'test,rr']
